//int numberA = 3;
//int numberB = 5;
//int result = numberA + numberB;
//Console.WriteLine(result);
int numberA = new Random().Next(1, 10);
int numberB = new Random().Next(1, 10);
int result = numberA + numberB;
Console.WriteLine(numberA);
Console.WriteLine(numberB);
Console.WriteLine(result);
